// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Используйте правильные ключи из вашего Supabase Dashboard
// Settings -> API -> Project URL и anon/public key
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://nwhofujrytcyvlouucvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53aG9mdWpyeXRjeXZsb3V1Y3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU0MjI5ODYsImV4cCI6MjEwMDk5ODk4Nn0.p6Z3EzLEerNtPqxaF-LuNS1IPq4ITU0rCAidIxht0ec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});